# LedgerCopilot — developer task runner.
# Thin wrappers over the documented commands so `git log` + `make help`
# stay in sync with how the project is actually run.

.DEFAULT_GOAL := help
.PHONY: help setup dev-api dev-worker dev-web check py-lint py-type py-test web-check migrate revision infra-up infra-down

help: ## List available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

setup: ## Install all deps (python + frontend)
	uv sync
	pnpm install

dev-api: ## Run the FastAPI app with reload (:8000)
	uv run uvicorn apps.api.main:app --reload

dev-worker: ## Run the arq pipeline worker
	uv run arq workers.pipeline.WorkerSettings

dev-web: ## Run the Next.js frontend (:3000)
	pnpm --filter web dev

check: py-lint py-type py-test web-check ## Run all quality gates

py-lint: ## ruff lint + format check
	uv run ruff check .
	uv run ruff format --check .

py-type: ## mypy (strict in pure packages)
	uv run mypy packages apps workers

py-test: ## pytest (unit + integration)
	uv run pytest

web-check: ## frontend lint + typecheck
	pnpm --filter web lint
	pnpm --filter web typecheck

migrate: ## Apply DB migrations
	uv run alembic upgrade head

revision: ## Create an autogenerated migration: make revision m="message"
	uv run alembic revision --autogenerate -m "$(m)"

infra-up: ## Start local postgres + redis + storage
	docker compose -f infra/docker-compose.dev.yml up -d

infra-down: ## Stop local infra
	docker compose -f infra/docker-compose.dev.yml down
