"""add_dead_letters_table

Revision ID: 25cbf4e46839
Revises: df37697dd16e
Create Date: 2026-05-29 21:17:03.334224+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '25cbf4e46839'
down_revision: str | None = 'df37697dd16e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('error_type', sa.String(length=256), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_case_id'), 'dead_letters', ['case_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_organization_id'), 'dead_letters', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dead_letters_organization_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_case_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    # ### end Alembic commands ###
