"""unique_name_and_soft_delete_prompt_versions

Revision ID: 83ce92ede619
Revises: f8b2c3d4e5a6
Create Date: 2026-05-31 00:31:34.658478+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '83ce92ede619'
down_revision: str | None = 'f8b2c3d4e5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'prompt_versions', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompt_versions', type_='unique')
    # ### end Alembic commands ###
