"""add_business_key_to_cases

Revision ID: dc75a14b152f
Revises: 99d18739ec43
Create Date: 2026-05-29 21:49:09.544286+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'dc75a14b152f'
down_revision: str | None = '99d18739ec43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('business_key', sa.String(length=512), nullable=True))
    op.create_index('ix_cases_org_business_key', 'cases', ['organization_id', 'business_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_org_business_key', table_name='cases')
    op.drop_column('cases', 'business_key')
    # ### end Alembic commands ###
