# Secret Manager — the single source of credentials injected into Cloud Run at
# runtime.
#
#   secret-key      → generated by Terraform (JWT signing key; no human handling).
#   database-url    → composed by Terraform from the Cloud SQL instance.
#   anthropic-api-key → value supplied OUT OF BAND (real provider key, repo-owner held):
#       echo -n "$KEY" | gcloud secrets versions add anthropic-api-key --data-file=-
#     The API/worker will not start until a version exists.

resource "random_password" "jwt_secret" {
  length  = 48
  special = false
}

# --- JWT signing key ---------------------------------------------------------
resource "google_secret_manager_secret" "secret_key" {
  secret_id = "secret-key"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "secret_key" {
  secret      = google_secret_manager_secret.secret_key.id
  secret_data = random_password.jwt_secret.result
}

# --- Database URL ------------------------------------------------------------
resource "google_secret_manager_secret" "database_url" {
  secret_id = "database-url"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}

resource "google_secret_manager_secret_version" "database_url" {
  secret      = google_secret_manager_secret.database_url.id
  secret_data = local.database_url
}

# --- Anthropic API key (version added out of band) ---------------------------
resource "google_secret_manager_secret" "anthropic_api_key" {
  secret_id = "anthropic-api-key"
  replication {
    auto {}
  }
  depends_on = [google_project_service.enabled]
}
